# Generated by Django 3.0.7 on 2020-07-01 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('birth_date', models.DateField()),
                ('type_user_choices', models.CharField(choices=[('ME', 'Member'), ('MA', 'Manager')], max_length=2)),
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
