# Generated by Django 3.0.7 on 2020-07-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='civility',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='association_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Association'),
            preserve_default=False,
        ),
    ]
