# Generated by Django 3.0.7 on 2020-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200702_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
