# Generated by Django 3.0.7 on 2020-07-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200708_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type_user_choices',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
