# Generated by Django 3.0.7 on 2020-07-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200709_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='re_email',
            field=models.EmailField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
