# Generated by Django 3.0.7 on 2020-07-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_customuser_re_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='association_id',
            new_name='association',
        ),
    ]
