# Generated by Django 3.0.7 on 2020-08-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200728_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='picture',
            field=models.ImageField(default='images/no_image.png', upload_to='images/'),
        ),
    ]
