# Generated by Django 3.0.7 on 2020-08-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200804_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='association',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Association'),
        ),
    ]
