# Generated by Django 3.0.7 on 2020-08-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200805_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='action',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='difficulty',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='mission',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='need',
            field=models.TextField(null=True),
        ),
    ]
