language: python
python:
  - '3.7'

# safelist
branches:
  only:
      - staging

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE='getup_project.settings'

services:
  - postgresql

script:
  - ./manage.py test tests