language: python
python:
  - '3.7'

# safelist
branches:
  only:
      - staging

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database getup;' -U acuffel

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE='getup_project.settings'

script:
  - ./manage.py test tests