language: python
python:
  - '3.7'

# safelist
branches:
  only:
      - staging

before_script:
  - pip install -r requirements.txt
  - python3 manage.py runserver &

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE='bp_project.settings'

script:
  - ./manage.py test tests