# Generated by Django 3.0.7 on 2020-07-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('association_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('association_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
                ('donor_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Donor')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Event')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.CustomUser')),
            ],
        ),
    ]
