# Generated by Django 3.0.7 on 2020-07-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200702_0803'),
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='association_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Association'),
        ),
        migrations.AlterField(
            model_name='event',
            name='association_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Association'),
        ),
        migrations.DeleteModel(
            name='Association',
        ),
    ]
