# Generated by Django 3.0.7 on 2020-07-31 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_auto_20200702_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='phone',
        ),
    ]
