# Generated by Django 3.0.7 on 2020-08-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_remove_donor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='association.Donor'),
        ),
    ]
